import html2canvas from "html2canvas";
import jsPDF from "jspdf";
import autoTable from 'jspdf-autotable'
import { useRef } from "react";
import { useNavigate } from "react-router-dom";
import {
  Button,
  Card,
  CardBody,
  CardHeader,
  Col,
  Container,
  Row,
  Table,
} from "reactstrap";

// ✅ Importar el logo desde assets
import Encabezado from "assets/img/brand/Encabezado.jpeg";


// Datos de inventario
const inventario = [
  {
    codigo: "TV40-01",
    nombre: "Escritorio",
    descripcion: "Para presentadores de los programas en vivo",
    cantidad: 1,
    ubicacion: "Set",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-02",
    nombre: "Escritorio",
    descripcion: "Para presentadores de los programas en vivo",
    cantidad: 1,
    ubicacion: "Set",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-03",
    nombre: "Escritorio",
    descripcion: "Para presentadores de los programas en vivo",
    cantidad: 1,
    ubicacion: "Set",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-04",
    nombre: "Escritorio",
    descripcion: "Para presentadores de los programas en vivo",
    cantidad: 1,
    ubicacion: "Set",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-05",
    nombre: "Silla",
    descripcion: "Para los conductores e invitados de los programas\nen vivo",
    cantidad: 1,
    ubicacion: "Set",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-06",
    nombre: "Silla",
    descripcion: "Para los conductores e invitados de los programas\nen vivo",
    cantidad: 1,
    ubicacion: "Set",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-07",
    nombre: "Silla",
    descripcion: "Para los conductores e invitados de los programas\nen vivo",
    cantidad: 1,
    ubicacion: "Set",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-08",
    nombre: "Cámara",
    descripcion: "Marca Panasonic para los programas en vivo",
    cantidad: 1,
    ubicacion: "Set",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-09",
    nombre: "Cámaras",
    descripcion: "Marca Sony para los programas en vivo",
    cantidad: 1,
    ubicacion: "Set",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-10",
    nombre: "Televisor",
    descripcion: "Marca Samsung para ver los programas en vivo en\nel set",
    cantidad: 1,
    ubicacion: "Set",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
    {
    codigo: "TV40-11",
    nombre: "Mesa",
    descripcion: "Para colocar el tv de los programas en vivo",
    cantidad: 1,
    ubicacion: "Set",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-12",
    nombre: "Tripode",
    descripcion: "En buen estado para las camaras",
    cantidad: 1,
    ubicacion: "Set",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-13",
    nombre: "Tripode",
    descripcion: "En buen estado para las camaras",
    cantidad: 1,
    ubicacion: "Set",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "Sin Uso",
  },
  {
    codigo: "TV40-14",
    nombre: "Tripode",
    descripcion: "En buen estado para las camaras",
    cantidad: 1,
    ubicacion: "Set",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "Sin Uso",
  },
  {
    codigo: "TV40-15",
    nombre: "Regleta",
    descripcion: "Color negro para conexiones electricas de las\ncamaras y el tv",
    cantidad: 1,
    ubicacion: "Set",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-16",
    nombre: "Lámpara",
    descripcion: "Para dar iluminación al set",
    cantidad: 1,
    ubicacion: "Set",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-17",
    nombre: "Lámpara",
    descripcion: "Para dar iluminación al set",
    cantidad: 1,
    ubicacion: "Set",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-18",
    nombre: "Mecha",
    descripcion: "Para video",
    cantidad: 1,
    ubicacion: "Set",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-19",
    nombre: "Mecha",
    descripcion: "Para video",
    cantidad: 1,
    ubicacion: "Set",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-20",
    nombre: "Mecha",
    descripcion: "Para video",
    cantidad: 1,
    ubicacion: "Set",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-21",
    nombre: "Mecha",
    descripcion: "Para audio",
    cantidad: 1,
    ubicacion: "Set",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-22",
    nombre: "Mecha",
    descripcion: "Para microfono",
    cantidad: 1,
    ubicacion: "Set",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-23",
    nombre: "Mecha",
    descripcion: "Para microfono",
    cantidad: 1,
    ubicacion: "Set",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-24",
    nombre: "Power",
    descripcion: "Completos en usos constantes",
    cantidad: 1,
    ubicacion: "Set",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "Sin Uso",
  },
  {
    codigo: "TV40-25",
    nombre: "Power",
    descripcion: "Completos en usos constantes",
    cantidad: 1,
    ubicacion: "Set",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "Sin Uso",
  },
  {
    codigo: "TV40-26",
    nombre: "Microfono",
    descripcion: "Con el respectivo pedestal para el audio de los\nprogramas en vivo",
    cantidad: 1,
    ubicacion: "Set",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-27",
    nombre: "Extractor",
    descripcion: "Sin utilizarse",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "Sin Uso",
  },
  {
    codigo: "TV40-28",
    nombre: "Televisor",
    descripcion: "Samsung para verificar la señal abierta",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-29",
    nombre: "Mueble",
    descripcion: "Para sostener el tv de señal abierta",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-30",
    nombre: "Computadora",
    descripcion: "Monitor LG con internet, verificar el whatsapp\ndel canal, teclado Dell, CPU Mega, mouse Genius,\nRAM de 2gb, sistema operativo de 64 bits y 152gb\nde disco duro",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-31",
    nombre: "Tricaster",
    descripcion: "NEWTEK de respuesto",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "Sin Uso",
  },
  {
    codigo: "TV40-32",
    nombre: "Mesa",
    descripcion: "Para sostener la pc del whatsapp, tricaster y\ncontrolador de cámaras",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-33",
    nombre: "Kit de cámaras",
    descripcion: "4 Camaras marca Swann y monitor Samsung, mouse\nSwann para monitoreo de las actividades dentro del\ncanal",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-34",
    nombre: "Regletas",
    descripcion: "Varias entradas de conexiones eléctricas para el\nequipo",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-35",
    nombre: "Regletas",
    descripcion: "Varias entradas de conexiones eléctricas para el\nequipo",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-36",
    nombre: "Regletas",
    descripcion: "Varias entradas de conexiones eléctricas para el\nequipo",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-37",
    nombre: "Silla",
    descripcion: "Plástica para los usuarios de controles",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-38",
    nombre: "Silla",
    descripcion: "Giratoria para el encargado de controles",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-39",
    nombre: "Televisor",
    descripcion: "Marca Toshiba monitor de la tricaster con mouse y\nteclado Newtek",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-40",
    nombre: "Consola",
    descripcion: "Para audio marca Soundcraft",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-41",
    nombre: "Mezcladora",
    descripcion: "Marca Datavideo para audio y video",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-42",
    nombre: "UPS",
    descripcion: "Brinda la energía para la tricaster y demás\nequipo del área de controles",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-43",
    nombre: "Tricaster",
    descripcion: "Control de video y audio Broadcast",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-44",
    nombre: "Computadora",
    descripcion: "Monitor Dell con teclado, mouse Genius utilizada\npara los anuncios, con Windows XP, 2GB de RAM,\n29.2GB de disco duro",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-45",
    nombre: "Computadora",
    descripcion: "Monitor Eizo, teclado Genius, mouse y CPU Dell\nutilizada para videos con Windows 7, 4GB de RAM,\n76.5GB de disco duro",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-46",
    nombre: "Computadora",
    descripcion: "Monitor Dell con teclado Bion, CPU Dell y mouse\nGenius utilizada para revisar el correo del canal\ncon Windows 7, RAM de 5GB, 148GB de disco duro",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-47",
    nombre: "Computadora",
    descripcion: "Monitor y teclado Dell, mouse, CPU HP utilizada\npara el streaming con Windows XP, RAM de 2.99GB y\n37.2GB de disco duro",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-48",
    nombre: "VH",
    descripcion: "Marca Sony",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-49",
    nombre: "VH",
    descripcion: "Marca RCA conectado a señal del cable",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-50",
    nombre: "Teléfono Fijo",
    descripcion: "Doble línea marca CONAIRPHONE",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-51",
    nombre: "Procesador de video",
    descripcion: "Grass valley group con 4 salidas de video y 1\nentrada",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-52",
    nombre: "DVD",
    descripcion: "Marca Philips",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-53",
    nombre: "Equipo de sonido",
    descripcion: "Marca Anwa para reproducir sonido de la\nprogramación",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-54",
    nombre: "Monitores pequeños",
    descripcion: "Para los previos de las cámaras señal de cable",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-55",
    nombre: "Monitores pequeños",
    descripcion: "Para los previos de las cámaras señal de cable",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-56",
    nombre: "Estructuras metálicas (beige)",
    descripcion: "Donde está colocado parte del equipo",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-57",
    nombre: "Estructuras metálicas (beige)",
    descripcion: "Donde está colocado parte del equipo",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-58",
    nombre: "Estructuras metálicas (beige)",
    descripcion: "Donde está colocado parte del equipo",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-59",
    nombre: "Películas",
    descripcion: "Utilizadas antes para reproducción",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "Sin Uso",
  },
  {
    codigo: "TV40-60",
    nombre: "Aire acondicionado",
    descripcion: "Cold confort de tamaño pequeño",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "Sin Uso",
  },
  {
    codigo: "TV40-61",
    nombre: "Extensión",
    descripcion: "Blanca para la conexión del equipo",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-62",
    nombre: "Estructura metálica (negra)",
    descripcion: "Donde está colocadas las películas",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-63",
    nombre: "Manos libres o Auriculares",
    descripcion: "Marca AKG",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-64",
    nombre: "Basurero",
    descripcion: "Para los desechos",
    cantidad: 1,
    ubicacion: "Controles",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-65",
    nombre: "Aire acondicionado",
    descripcion: "Cold confort de tamaño pequeño instalado en el\ncuarto del transmisor",
    cantidad: 1,
    ubicacion: "Cuarto del Transmisor",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-66",
    nombre: "Mesa",
    descripcion: "La cual sostiene equipo en el cuarto del\ntransmisor",
    cantidad: 1,
    ubicacion: "Cuarto del Transmisor",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-67",
    nombre: "UPS",
    descripcion: "Energía en el área del transmisor",
    cantidad: 1,
    ubicacion: "Cuarto del Transmisor",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-68",
    nombre: "Transmisor",
    descripcion: "Con excitador que genera la señal a diario y un\ndemodulador de video",
    cantidad: 1,
    ubicacion: "Cuarto del Transmisor",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-69",
    nombre: "Transmisor",
    descripcion: "Con excitador que genera la señal a diario y un\ndemodulador de video",
    cantidad: 1,
    ubicacion: "Cuarto del Transmisor",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-70",
    nombre: "Escritorio",
    descripcion: "Para el equipo del camarógrafo",
    cantidad: 1,
    ubicacion: "Redacción",
    asignado: "Oscar",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-71",
    nombre: "Escritorio",
    descripcion: "Para el periodista",
    cantidad: 1,
    ubicacion: "Redacción",
    asignado: "Héctor",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-72",
    nombre: "Mesa",
    descripcion: "Para objetos varios del camarógrafo y periodista",
    cantidad: 1,
    ubicacion: "Redacción",
    asignado: "Héctor y Oscar",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-73",
    nombre: "Cámara",
    descripcion: "Marca Panasonic utilizada para entrevistas",
    cantidad: 1,
    ubicacion: "Redacción",
    asignado: "Oscar",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-74",
    nombre: "Cámara",
    descripcion: "Sin utilizarse",
    cantidad: 1,
    ubicacion: "Redacción",
    asignado: "",
    valor: "",
    observacion: "Sin Uso",
  },
  {
    codigo: "TV40-75",
    nombre: "Cámara",
    descripcion: "Sin utilizarse",
    cantidad: 1,
    ubicacion: "Redacción",
    asignado: "",
    valor: "",
    observacion: "Sin Uso",
  },
  {
    codigo: "TV40-76",
    nombre: "Micrófono",
    descripcion: "Utilizado en las entrevistas",
    cantidad: 1,
    ubicacion: "Redacción",
    asignado: "Héctor",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-77",
    nombre: "Televisor",
    descripcion: "Marca Daevoo con señal por cable",
    cantidad: 1,
    ubicacion: "Redacción",
    asignado: "Oscar",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-78",
    nombre: "Computadora",
    descripcion: "Monitor y mouse Dell, teclado RLIP, parlante\nGenius para editar reportajes con 4GB RAM, Windows\n7, 74.4GB disco",
    cantidad: 1,
    ubicacion: "Redacción",
    asignado: "Oscar",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-79",
    nombre: "Extractor",
    descripcion: "Uno marca Sankey destinado al área de redacción",
    cantidad: 2,
    ubicacion: "Redacción",
    asignado: "Héctor y Oscar",
    valor: "",
    observacion: "1 en uso, otro inhabilitado",
  },
  {
    codigo: "TV40-80",
    nombre: "Batería",
    descripcion: "Para la cámara que utiliza el camarógrafo",
    cantidad: 1,
    ubicacion: "Redacción",
    asignado: "Oscar",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-81",
    nombre: "Batería",
    descripcion: "Para la cámara que utiliza el camarógrafo",
    cantidad: 1,
    ubicacion: "Redacción",
    asignado: "Oscar",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-82",
    nombre: "Cargador",
    descripcion: "Para cargar las baterías de las cámaras",
    cantidad: 1,
    ubicacion: "Redacción",
    asignado: "Oscar",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-83",
    nombre: "Basurero",
    descripcion: "Para los desechos",
    cantidad: 1,
    ubicacion: "Redacción",
    asignado: "Héctor y Oscar",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-84",
    nombre: "Silla",
    descripcion: "Para el uso del periodista",
    cantidad: 1,
    ubicacion: "Redacción",
    asignado: "Héctor",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-85",
    nombre: "Silla",
    descripcion: "Para el uso del camarógrafo",
    cantidad: 1,
    ubicacion: "Redacción",
    asignado: "Oscar",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-86",
    nombre: "Televisor",
    descripcion: "Instalado en la sala del canal conectado al\nprocesador para previo de la señal",
    cantidad: 1,
    ubicacion: "General",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-87",
    nombre: "Computadora",
    descripcion: "Monitor, CPU, teclado Dell con mouse One para\nlabores de encargado de mercadeo con lector de\nDVD, 73.2GB de disco duro, RAM de 5GB, Windows 7\nsistema operativo de 64 bits",
    cantidad: 1,
    ubicacion: "General",
    asignado: "Allan",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-88",
    nombre: "Escritorio",
    descripcion: "Está instalada la PC de mercadeo un poco\ndeteriorado",
    cantidad: 1,
    ubicacion: "General",
    asignado: "Allan",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-89",
    nombre: "Silla",
    descripcion: "Para el encargado de mercadeo",
    cantidad: 1,
    ubicacion: "General",
    asignado: "Allan",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-90",
    nombre: "Archivero",
    descripcion: "Para documentos importantes de la administración",
    cantidad: 1,
    ubicacion: "General",
    asignado: "Yaret",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-91",
    nombre: "Juego de sala",
    descripcion: "Consta de 4 muebles para el público en general\nque visita al canal",
    cantidad: 1,
    ubicacion: "General",
    asignado: "Todos",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-92",
    nombre: "Oasis",
    descripcion: "Para el agua",
    cantidad: 1,
    ubicacion: "General",
    asignado: "Todos",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-93",
    nombre: "Extensión",
    descripcion: "Para la conexión de la PC",
    cantidad: 1,
    ubicacion: "General",
    asignado: "Allan",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-94",
    nombre: "Mesa",
    descripcion: "De centro en la sala general",
    cantidad: 1,
    ubicacion: "General",
    asignado: "Todos",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-95",
    nombre: "Percoladora",
    descripcion: "Marca Toastmaster para el uso de los empleados",
    cantidad: 1,
    ubicacion: "General",
    asignado: "Todos",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-96",
    nombre: "Microondas",
    descripcion: "Marca Samsung para el uso de los empleados",
    cantidad: 1,
    ubicacion: "General",
    asignado: "Todos",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-97",
    nombre: "Mesa",
    descripcion: "Para colocar el microondas",
    cantidad: 1,
    ubicacion: "General",
    asignado: "Todos",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-98",
    nombre: "Mesa",
    descripcion: "Para colocar la percoladora",
    cantidad: 1,
    ubicacion: "General",
    asignado: "Todos",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-99",
    nombre: "Tazas o Vasos",
    descripcion: "Para el uso de los empleados",
    cantidad: 4,
    ubicacion: "General",
    asignado: "Todos",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-100",
    nombre: "Basurero",
    descripcion: "Para desechos",
    cantidad: 1,
    ubicacion: "General",
    asignado: "Allan",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-101",
    nombre: "Microbús",
    descripcion: "Para diligencias laborales",
    cantidad: 1,
    ubicacion: "General",
    asignado: "Yaret",
    valor: "",
    observacion: "En uso",
  },
    {
    codigo: "TV40-102",
    nombre: "Mueble",
    descripcion: "De madera para fotos y objetos variados de la\ngerencia",
    cantidad: 1,
    ubicacion: "Gerencia",
    asignado: "Lic Gamez",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-103",
    nombre: "Silla",
    descripcion: "Para el uso de asistente de gerencia",
    cantidad: 1,
    ubicacion: "Gerencia",
    asignado: "Lic Gamez",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-104",
    nombre: "Mueble",
    descripcion: "De madera para computadora de asistente de\ngerencia",
    cantidad: 1,
    ubicacion: "Gerencia",
    asignado: "Lic Gamez",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-105",
    nombre: "Mueble",
    descripcion: "Para las visitas/clientes",
    cantidad: 1,
    ubicacion: "Gerencia",
    asignado: "Lic Gamez",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-106",
    nombre: "Computadora",
    descripcion: "Con monitor Samsung, mouse y teclado Genius, CPU\nDell",
    cantidad: 1,
    ubicacion: "Gerencia",
    asignado: "Lic Gamez",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-107",
    nombre: "Ventilador",
    descripcion: "Marca Goldstar para asistente de gerencia",
    cantidad: 1,
    ubicacion: "Gerencia",
    asignado: "Lic Gamez",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-108",
    nombre: "Teléfono fijo",
    descripcion: "Marca Sharp UX P200",
    cantidad: 1,
    ubicacion: "Gerencia",
    asignado: "Lic Gamez",
    valor: "",
    observacion: "Sin Uso",
  },
  {
    codigo: "TV40-109",
    nombre: "Teléfono fijo",
    descripcion: "Marca Alcatel",
    cantidad: 1,
    ubicacion: "Gerencia",
    asignado: "Lic Gamez",
    valor: "",
    observacion: "Sin Uso",
  },
  {
    codigo: "TV40-110",
    nombre: "Archivero",
    descripcion: "Para documentos de la gerencia",
    cantidad: 1,
    ubicacion: "Gerencia",
    asignado: "Lic Gamez",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-111",
    nombre: "Estante",
    descripcion: "Para libros y colocar el TV",
    cantidad: 1,
    ubicacion: "Gerencia",
    asignado: "Lic Gamez",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-112",
    nombre: "Televisor",
    descripcion: "Marca Sony",
    cantidad: 1,
    ubicacion: "Gerencia",
    asignado: "Lic Gamez",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-113",
    nombre: "Regleta",
    descripcion: "Para conexiones eléctricas",
    cantidad: 1,
    ubicacion: "Gerencia",
    asignado: "Lic Gamez",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-114",
    nombre: "Escritorio",
    descripcion: "Para uso de la gerencia",
    cantidad: 1,
    ubicacion: "Gerencia",
    asignado: "Lic Gamez",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-115",
    nombre: "Computadora",
    descripcion: "Incluye parlantes, solo para trabajos de la\ngerencia",
    cantidad: 1,
    ubicacion: "Gerencia",
    asignado: "Lic Gamez",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-116",
    nombre: "Impresora",
    descripcion: "Para la impresión de documentos necesarios de la\ngerencia, mercadeo u otros departamentos",
    cantidad: 1,
    ubicacion: "Gerencia",
    asignado: "Lic Gamez",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-117",
    nombre: "Refrigeradora",
    descripcion: "Para servicios del gerente",
    cantidad: 1,
    ubicacion: "Gerencia",
    asignado: "Lic Gamez",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-118",
    nombre: "Basurero",
    descripcion: "Para desechos sólidos",
    cantidad: 1,
    ubicacion: "Gerencia",
    asignado: "Lic Gamez",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-119",
    nombre: "Basurero",
    descripcion: "Para desechos sólidos",
    cantidad: 1,
    ubicacion: "Gerencia",
    asignado: "Lic Gamez",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-120",
    nombre: "Silla",
    descripcion: "Giratoria para el gerente",
    cantidad: 1,
    ubicacion: "Gerencia",
    asignado: "Lic Gamez",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-121",
    nombre: "Regleta",
    descripcion: "Color gris para utilizarla en ocasiones",
    cantidad: 1,
    ubicacion: "Bodega",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "Usos casuales",
  },
  {
    codigo: "TV40-122",
    nombre: "Extensión",
    descripcion: "Blanca para ocasiones",
    cantidad: 1,
    ubicacion: "Bodega",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "Usos casuales",
  },
  {
    codigo: "TV40-123",
    nombre: "Extensión",
    descripcion: "Anaranjada para ocasiones",
    cantidad: 1,
    ubicacion: "Bodega",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "Usos casuales",
  },
  {
    codigo: "TV40-124",
    nombre: "Antena",
    descripcion: "Para transmisiones fuera del canal",
    cantidad: 1,
    ubicacion: "Bodega",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "Usos casuales",
  },
  {
    codigo: "TV40-125",
    nombre: "Trípode",
    descripcion: "Para colocar la antena de transmisiones",
    cantidad: 1,
    ubicacion: "Bodega",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "Usos casuales",
  },
  {
    codigo: "TV40-126",
    nombre: "Antena",
    descripcion: "Para TV y captar la señal abierta",
    cantidad: 1,
    ubicacion: "Bodega",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "Sin uso",
  },
  {
    codigo: "TV40-127",
    nombre: "Cassette",
    descripcion: "Variados para utilizarlos en ocasiones",
    cantidad: "",
    ubicacion: "Bodega",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "Sin uso",
  },
  {
    codigo: "TV40-128",
    nombre: "Mechas",
    descripcion: "Para video",
    cantidad: "",
    ubicacion: "Bodega",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "Usos casuales",
  },
  {
    codigo: "TV40-129",
    nombre: "Mechas",
    descripcion: "Para sonido",
    cantidad: "",
    ubicacion: "Bodega",
    asignado: "Heber y Marlón",
    valor: "",
    observacion: "Usos casuales",
  },
  {
    codigo: "TV40-130",
    nombre: "Escritorio",
    descripcion: "En los cuales está el equipo de trabajo necesario",
    cantidad: 1,
    ubicacion: "Administración",
    asignado: "Yaret",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-131",
    nombre: "Escritorio",
    descripcion: "En el cual está equipo que no es utilizado pero\nestá en buen estado",
    cantidad: 1,
    ubicacion: "Administración",
    asignado: "Yaret",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-132",
    nombre: "Televisor",
    descripcion: "Marca LG utilizado por el administrador",
    cantidad: 1,
    ubicacion: "Administración",
    asignado: "Yaret",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-133",
    nombre: "Televisor",
    descripcion: "Marca Samsung el cual incluye parlantes y una\ncámara conectado al mismo DVD marca RCA con un CPU\nXtech en el cual se editan los spots",
    cantidad: 1,
    ubicacion: "Administración",
    asignado: "Yaret",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-134",
    nombre: "Consola",
    descripcion: "Marca Alesis para el audio",
    cantidad: 1,
    ubicacion: "Administración",
    asignado: "Yaret",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-135",
    nombre: "Parlante",
    descripcion: "Marca RCA conectado al TV Samsung",
    cantidad: 1,
    ubicacion: "Administración",
    asignado: "Yaret",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-136",
    nombre: "Pedestal",
    descripcion: "Para micrófono",
    cantidad: 1,
    ubicacion: "Administración",
    asignado: "Yaret",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-137",
    nombre: "Micrófono",
    descripcion: "Utilizado para grabar el audio de los spots",
    cantidad: 1,
    ubicacion: "Administración",
    asignado: "Yaret",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-138",
    nombre: "Mechas",
    descripcion: "De sonido para el micrófono",
    cantidad: 1,
    ubicacion: "Administración",
    asignado: "Yaret",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-139",
    nombre: "Televisor",
    descripcion: "Marca Philips",
    cantidad: 1,
    ubicacion: "Administración",
    asignado: "Yaret",
    valor: "",
    observacion: "Sin Uso",
  },
  {
    codigo: "TV40-140",
    nombre: "Equipo de sonido",
    descripcion: "Marca Philips",
    cantidad: 1,
    ubicacion: "Administración",
    asignado: "Yaret",
    valor: "",
    observacion: "Sin Uso",
  },
  {
    codigo: "TV40-141",
    nombre: "Monitores",
    descripcion: "Uno marca LG y otro marca Syncmaster en perfecto\nestado",
    cantidad: 1,
    ubicacion: "Administración",
    asignado: "Yaret",
    valor: "",
    observacion: "Sin Uso",
  },
  {
    codigo: "TV40-142",
    nombre: "VTR",
    descripcion: "Marca Newtek",
    cantidad: 1,
    ubicacion: "Administración",
    asignado: "Yaret",
    valor: "",
    observacion: "Sin Uso",
  },
  {
    codigo: "TV40-143",
    nombre: "Consola",
    descripcion: "Marca Alesis para audio",
    cantidad: 1,
    ubicacion: "Administración",
    asignado: "Yaret",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-144",
    nombre: "UPS",
    descripcion: "CDP para la energía del equipo del área",
    cantidad: 1,
    ubicacion: "Administración",
    asignado: "Yaret",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-145",
    nombre: "Consola",
    descripcion: "Marca Mixer para el audio la cual no es utilizada\nactualmente",
    cantidad: 1,
    ubicacion: "Administración",
    asignado: "Yaret",
    valor: "",
    observacion: "Sin Uso",
  },
  {
    codigo: "TV40-146",
    nombre: "Router",
    descripcion: "Para interconectar computadoras que funcionan en\nel marco de una red",
    cantidad: 1,
    ubicacion: "Administración",
    asignado: "Yaret",
    valor: "",
    observacion: "Sin Uso",
  },
  {
    codigo: "TV40-147",
    nombre: "Router",
    descripcion: "Para interconectar computadoras que funcionan en\nel marco de una red",
    cantidad: 1,
    ubicacion: "Administración",
    asignado: "Yaret",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-148",
    nombre: "Dron",
    descripcion: "Marca Tello",
    cantidad: 1,
    ubicacion: "Administración",
    asignado: "Yaret",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-149",
    nombre: "Regleta",
    descripcion: "Para las conexiones eléctricas del equipo\nutilizado en el área",
    cantidad: 1,
    ubicacion: "Administración",
    asignado: "Yaret",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-150",
    nombre: "Silla",
    descripcion: "Para el administrador",
    cantidad: 1,
    ubicacion: "Administración",
    asignado: "Yaret",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-151",
    nombre: "Ventilador",
    descripcion: "Para el uso del administrador",
    cantidad: 1,
    ubicacion: "Administración",
    asignado: "Yaret",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-152",
    nombre: "Basurero",
    descripcion: "Para desechos sólidos",
    cantidad: 1,
    ubicacion: "Administración",
    asignado: "Yaret",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-153",
    nombre: "Mezcladora",
    descripcion: "De video y sonido marca Datavideo",
    cantidad: 1,
    ubicacion: "Administración",
    asignado: "Yaret",
    valor: "",
    observacion: "En uso",
  },
  {
    codigo: "TV40-154",
    nombre: "Cámara",
    descripcion: "Se utiliza una para tomas para los spots",
    cantidad: 1,
    ubicacion: "Administración",
    asignado: "Yaret",
    valor: "",
    observacion: "Usos casuales",
  },
  {
    codigo: "TV40-155",
    nombre: "Cámara",
    descripcion: "Para las transmisiones en vivo fuera del canal",
    cantidad: 1,
    ubicacion: "Administración",
    asignado: "Yaret",
    valor: "",
    observacion: "Usos casuales",
  },
  {
    codigo: "TV40-156",
    nombre: "Cámara",
    descripcion: "Sirve de puente o para copias la cual está\ndefectuosa",
    cantidad: 1,
    ubicacion: "Administración",
    asignado: "Yaret",
    valor: "",
    observacion: "Usos casuales",
  },
  {
    codigo: "TV40-157",
    nombre: "Base de comunicación",
    descripcion: "Marca KENWOOD con su propia fuente de poder y la \nantena",
    cantidad: 1,
    ubicacion: "",
    asignado: "",
    valor: "",
    observacion: "En uso",
  },
];


const ReporteInventario = () => {
  const printRef = useRef();
  const navigate = useNavigate();

 const handleDownloadPDF = async () => {
    const pdf = new jsPDF("p", "mm", "a4");

    // 📌 Márgenes
    const margin = 15;

    // 📌 Encabezado de imagen
    const headerImg = new Image();
    headerImg.src = Encabezado;
    await new Promise((resolve) => {
      headerImg.onload = resolve;
    });

    const pdfWidth = pdf.internal.pageSize.getWidth();
    const contentWidth = pdfWidth - margin * 2;

    // Calcular altura del encabezado proporcional
    const aspectRatio = headerImg.width / headerImg.height;
    const headerHeight = contentWidth / aspectRatio;

    pdf.addImage(headerImg, "PNG", margin, margin, contentWidth, headerHeight);

    // 📌 Título debajo del encabezado
    const startY = margin + headerHeight + 10;
    pdf.setFontSize(20);
    pdf.setFont("helvetica", "bold");
    pdf.text("INVENTARIO", pdfWidth / 2, startY, { align: "center" });

    // 📌 Tabla
    autoTable(pdf, {
      startY: startY + 8,
      head: [["Código", "Nombre", "Descripción", "Cantidad", "Ubicación", "Asignado", "Observación"]],
      body: inventario.map(item => [
        item.codigo,
        item.nombre,
        item.descripcion,
        item.cantidad,
        item.ubicacion,
        item.asignado,
        item.observacion,
      ]),
      styles: { fontSize: 8, cellPadding: 2, overflow: "linebreak" },
      headStyles: { fillColor: [41, 128, 185], textColor: 255 },
      theme: "grid",
      margin: { left: margin, right: margin, bottom: margin },
    });

    // 📌 Pie de página (Página X de Y)
    const pageCount = pdf.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i);
      pdf.setFontSize(10);
      pdf.text(
        `Página ${i} de ${pageCount}`,
        pdfWidth / 2,
        pdf.internal.pageSize.getHeight() - 10,
        { align: "center" }
      );
    }

    pdf.save("inventario_canal40.pdf");
  };



  return (
    <>
      <style>
        {`
        .bg-gradient-info {
          background: linear-gradient(87deg, #11cdef 0, #1171ef 100%) !important;
        }
        .thead-light th {
          background-color: #eaf4fb;
          color: #4a4a4a;
        }
        .card-hover {
          transition: all 0.3s ease;
          cursor: pointer;
          border-radius: 10px;
        }
        .card-hover:hover {
          transform: scale(1.02);
          box-shadow: 0 6px 20px rgba(0, 0, 0, 0.2);
        }
        `}
      </style>

      <div className="header bg-gradient-info pb-8 pt-5 pt-md-8 d-print-none">
        <Container fluid>
          <Row className="justify-content-center mb-4">
            <Col xl="10" className="text-center">
            </Col>
          </Row>
        </Container>
      </div>

      <Container className="mt--7" fluid>
        <Row className="justify-content-center">
          <Col xl="10">
            <Card className="shadow card-hover">
              <CardHeader className="bg-info text-white text-center d-print-none" />
              <CardBody>
                <div ref={printRef}>
                  <div className="d-flex align-items-center mb-3">
                    
                    <div className="text-center w-100">
                      <h1>I N V E N T A R I O</h1>
                      <p>{new Date().toLocaleDateString()}</p>
                    </div>
                  </div>

                  <Table bordered responsive>
                    <thead className="thead-light">
                      <tr>
                        <th>Código</th>
                        <th>Nombre del equipo</th>
                        <th>Descripción</th>
                        <th>Cantidad</th>
                        <th>Ubicación</th>
                        <th>Asignado</th>
                        <th>Valor</th>
                        <th>Observación</th>
                      </tr>
                    </thead>
                    <tbody>
                      {inventario.map((item, index) => (
                        <tr key={index}>
                          <td>{item.codigo}</td>
                          <td>{item.nombre}</td>
                          <td style={{whiteSpace: 'pre-line'}}>{item.descripcion}</td>
                          <td>{item.cantidad}</td>
                          <td>{item.ubicacion}</td>
                          <td>{item.asignado}</td>
                          <td>{item.valor}</td>
                          <td>{item.observacion}</td>
                        </tr>
                      ))}
                    </tbody>
                  </Table>
                </div>

                <div className="text-center d-print-none mt-4">
                  <Button color="success" onClick={handleDownloadPDF}>
                    Descargar PDF
                  </Button>
                </div>
                
              </CardBody>
            </Card>
          </Col>
        </Row>
      </Container>
    </>
  );
};

export default ReporteInventario;
